version: "3.7"
services:
  app:
    build: .
    image: revalle88/sioserver:latest
    container_name: sioserver_app
    ports:
      - 6558:8080
    command: python sioserver.py
    volumes:
      - ./sioserver.py:/app/sioserver.py
      - ./index.html:/app/index.html
    depends_on:
      - redis
    restart: always
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.5
    container_name: sioserver_redis
    ports:
     - 6371:6379
    volumes:
      - ./data/redis:/data
    hostname: redis
